// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoPNuSx72yP-fpW_tBznISVecl0lory-s',
    appId: '1:689782726536:web:22bb21920c4841e5f3643d',
    messagingSenderId: '689782726536',
    projectId: 'flutter-clean-demo',
    authDomain: 'flutter-clean-demo.firebaseapp.com',
    storageBucket: 'flutter-clean-demo.appspot.com',
    measurementId: 'G-92NFQJM85N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvM2xWXGuE1hCU1I0_YHZopMHtuvdgrhY',
    appId: '1:689782726536:android:237eeeb22dd2446bf3643d',
    messagingSenderId: '689782726536',
    projectId: 'flutter-clean-demo',
    storageBucket: 'flutter-clean-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_fsMEi8o9Jb3tf3m5cHPNSJu28sIk3ww',
    appId: '1:689782726536:ios:ec56a0e6c7e63088f3643d',
    messagingSenderId: '689782726536',
    projectId: 'flutter-clean-demo',
    storageBucket: 'flutter-clean-demo.appspot.com',
    iosBundleId: 'com.example.cleanArchitectureDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_fsMEi8o9Jb3tf3m5cHPNSJu28sIk3ww',
    appId: '1:689782726536:ios:8e9c82d4b1abe702f3643d',
    messagingSenderId: '689782726536',
    projectId: 'flutter-clean-demo',
    storageBucket: 'flutter-clean-demo.appspot.com',
    iosBundleId: 'com.example.cleanArchitectureDemo.RunnerTests',
  );
}
