name: clean_architecture_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Icons
  cupertino_icons: ^1.0.6
  ionicons: ^0.2.2

  # Networking
  retrofit: ^4.0.1
  logger: ^2.0.2
  dio: ^5.3.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  http: ^1.1.0

  # State management
  flutter_bloc: ^8.1.3

  # Firebase
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.3.5
  firebase_remote_config: ^4.2.5

  # DI
  get_it: ^7.6.4

  # Route
  go_router: ^10.2.0

  # Async
  async: ^2.11.0

  # Others
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  path_provider: ^2.1.1

  dartx: ^1.2.0
  either_dart:
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1

  # Connectivity
  internet_connection_checker: ^1.0.0+1

  # Localization
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ">=5.0.0 <6.0.0"
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0

